kind: pipeline
type: docker
name: default

steps:
  - name: run-cypress-tests
    image: cypress/included:13.14.2
    environment:
      CYPRESS_baseUrl: http://server:8080
      REACT_APP_API_URL:
        from_secret: REACT_APP_API_URL
      CYPRESS_screenshotsFolder: cypress/screenshots/${DRONE_BUILD_NUMBER}
      CYPRESS_videosFolder: cypress/videos/${DRONE_BUILD_NUMBER}
    commands:
      - npx wait-on http://server:8080
      - cypress run
    depends_on:
      - server
    artifacts:
      paths:
        - cypress/screenshots/${DRONE_BUILD_NUMBER}/**
        - cypress/videos/${DRONE_BUILD_NUMBER}/**

  - name: upload-screenshots
    image: plugins/s3
    settings:
      bucket: cypress
      region: us-east-1
      source: cypress/screenshots/${DRONE_BUILD_NUMBER}/** 
      target: /drone-screenshots/${DRONE_BUILD_NUMBER}/
      access_key: 
        from_secret: MINIO_ACCESS_KEY
      secret_key: 
        from_secret: MINIO_SECRET_KEY
      endpoint: https://evolution-minio.geoq4d.easypanel.host
      path_style: true
    when:
      status: [ success, failure ]
    depends_on:
      - run-cypress-tests

  - name: upload-videos
    image: plugins/s3
    settings:
      bucket: cypress
      region: us-east-1
      source: cypress/videos/${DRONE_BUILD_NUMBER}/** 
      target: /drone-videos/${DRONE_BUILD_NUMBER}/
      access_key: 
        from_secret: MINIO_ACCESS_KEY
      secret_key: 
        from_secret: MINIO_SECRET_KEY
      endpoint: https://evolution-minio.geoq4d.easypanel.host
      path_style: true
    when:
      status: [ success, failure ]
    depends_on:
      - run-cypress-tests

services:
  - name: server
    image: node:21
    environment:
      PORT: 8080
      REACT_APP_API_URL:
        from_secret: http://localhost:5050/api
    commands:
      - yarn install
      - yarn start
