kind: pipeline
type: docker
name: default

steps:
  - name: install-dependencies
    image: node:21
    commands:
      - yarn install

  - name: install-cypress
    image: cypress/included:13.6.3
    commands:
      - cypress install

  - name: start-application
    image: node:21
    commands:
      - yarn start &
    environment:
      PORT: 8080
    detach: true

 - name: wait-for-server
    image: busybox
    commands:
      - sleep 50

  - name: run-cypress-tests
    image: cypress/included:13.6.3
    environment:
      CYPRESS_baseUrl: http://localhost:8080
    commands:
      - yarn run cypress run

cache:
  paths:
    - /root/.cache/Cypress
    - node_modules
