kind: pipeline
type: docker
name: default

steps:
  - name: waiton
    image: akhenakh/drone-waiton:1.0
    pull: always
    settings:
      globaltimeout: 300s
      urltimeout: 10s
      urls:
        - http://server:8080

  - name: run-cypress-tests
    image: cypress/included:13.14.2
    commands:
      - cypress run
    environment:
      CYPRESS_baseUrl: http://server:8080
    depends_on:
      - waiton

services:
  - name: server
    image: node:21
    environment:
      PORT: 8080
    commands:
      - yarn install
      - yarn start
