kind: pipeline
type: docker
name: default

steps:
  - name: run-cypress-tests
    image: cypress/included:13.14.2
    environment:
      CYPRESS_baseUrl: http://server:8080 # Cypress acessa o servidor pelo nome do serviço
      REACT_APP_API_URL: http://localhost:5050/api
    commands:
      - npx wait-on http://server:8080 # Espera o servidor estar acessível
      - cypress install
      - cypress run
    depends_on:
      - server

services:
  - name: server
    image: node:21
    environment:
      PORT: 8080
      REACT_APP_API_URL: http://localhost:5050/api
    commands:
      - yarn install
      - yarn start
