kind: pipeline
type: docker
name: default

steps:
  - name: run-cypress-tests
    image: cypress/included:13.14.2
    environment:
      CYPRESS_baseUrl: http://server:8080 # Cypress acessa o servidor pelo nome do serviço
    commands:
      - cypress run
    depends_on:
      - server

services:
  - name: server
    image: node:21
    environment:
      PORT: 8080
    commands:
      - yarn install # Instala as dependências antes de iniciar o servidor
      - yarn start
