kind: pipeline
type: docker
name: default

steps:
  - name: install-and-start-server
    image: node:21
    commands:
      - yarn install
      - yarn start &
    detach: true # Inicia o servidor em segundo plano sem bloquear o pipeline

  - name: run-cypress-tests
    image: cypress/included:13.14.2
    commands:
      - npx wait-on http://localhost:8080 # Aguarda o servidor estar acessível
      - cypress run
    environment:
      CYPRESS_baseUrl: http://localhost:8080
    depends_on:
      - install-and-start-server
