kind: pipeline
type: docker
name: default

steps:
  - name: install-deps
    image: node:21
    commands:
      - yarn install
    cache:
      key: node-modules-cache
      paths:
        - node_modules

  - name: run-cypress-tests
    image: cypress/included:13.14.2
    environment:
      CYPRESS_baseUrl: http://server:8080 # O Cypress acessa o servidor pelo nome do serviço
    commands:
      - cypress run
    depends_on:
      - server

services:
  - name: server
    image: node:21
    environment:
      PORT: 8080
    commands:
      - yarn start
