kind: pipeline
type: docker
name: default

steps:
  - name: install-dependencies
    image: node:21
    commands:
      - yarn install
    cache:
      key: node-modules-cache
      paths:
        - node_modules

  - name: start-application
    image: node:21
    commands:
      - yarn start &
      - sleep 60 # Espera 30 segundos para garantir que o servidor esteja rodando
      - curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8080 || echo "Failed to connect to server" # Tenta 5 vezes, com 5s entre tentativas
      - echo "Server is running" # Exibe log de sucesso se a conexão funcionar
    environment:
      PORT: 8080

  - name: run-cypress-tests
    image: cypress/included:13.14.2
    environment:
      CYPRESS_baseUrl: http://localhost:8080
    commands:
      - cypress run

cache:
  paths:
    - node_modules
