kind: pipeline
type: docker
name: default

steps:
  - name: run-cypress-tests
    image: cypress/included:13.14.2
    environment:
      CYPRESS_baseUrl: http://server:8080
      REACT_APP_API_URL: http://localhost:5050/api
    commands:
      - npx wait-on http://server:8080
      - cypress run
    depends_on:
      - server
    artifacts:
      paths:
        - cypress/screenshots

  - name: upload-screenshots
    image: plugins/s3
    settings:
      bucket: cypress
      region: us-east-1
      source: cypress/screenshots/*
      target: /drone-screenshots/
      access_key: ${MINIO_ACCESS_KEY}
      secret_key: ${MINIO_SECRET_KEY}
      endpoint: https://evolution-minio.geoq4d.easypanel.host
      path_style: true
    when:
      status: [ success, failure ]

services:
  - name: server
    image: node:21
    environment:
      PORT: 8080
      REACT_APP_API_URL: http://localhost:5050/api
    commands:
      - yarn install
      - yarn start
