kind: pipeline
type: docker
name: default

steps:
  - name: install-dependencies
    image: node:21
    commands:
      - yarn install
    cache:
      key: node-modules-cache
      paths:
        - node_modules

  - name: clear-cypress-cache
    image: cypress/included:13.14.2
    commands:
      - rm -rf /root/.cache/Cypress
    depends_on:
      - install-dependencies

  - name: install-cypress
    image: cypress/included:13.14.2
    commands:
      - cypress install
    depends_on:
      - clear-cypress-cache

  - name: start-application
    image: node:21
    commands:
      - yarn start &
      - >
        until curl --output /dev/null --silent --head --fail http://localhost:8080;
        do echo "Waiting for the server..."; sleep 5;
        done
      - echo "Server is running!"
    environment:
      PORT: 8080
    depends_on:
      - install-cypress

  - name: run-cypress-tests
    image: cypress/included:13.14.2
    environment:
      CYPRESS_baseUrl: http://localhost:8080
    commands:
      - cypress run
    depends_on:
      - start-application

cache:
  paths:
    - node_modules
