kind: pipeline
type: docker
name: default

steps:
  - name: install-dependencies
    image: node:21
    commands:
      - yarn install
    cache:
      key: node-modules-cache
      paths:
        - node_modules

  - name: install-cypress
    image: cypress/included:13.14.2
    commands:
      - cypress install

  - name: start-application
    image: node:21
    commands:
      - yarn start &
      - sleep 50
      - curl --retry 6 --retry-delay 5 --retry-connrefused http://localhost:8080 || echo "Failed to connect to server"
      - echo "Server is running"
    environment:
      PORT: 8080

  - name: run-cypress-tests
    image: cypress/included:13.14.2
    environment:
      CYPRESS_baseUrl: http://localhost:8080
    commands:
      - yarn run cypress run

cache:
  paths:
    - node_modules
