kind: pipeline
type: docker
name: default

steps:
  - name: run-cypress-tests
    image: cypress/included:13.14.2
    commands:
      - npm install wait-on # Instala o wait-on via npm
      - npx wait-on http://server:8080 # Espera o servidor estar acessível
      - cypress install
      - cypress run
    environment:
      CYPRESS_baseUrl: http://server:8080
    depends_on:
      - server

services:
  - name: server
    image: node:21
    environment:
      PORT: 8080
    commands:
      - yarn install
      - yarn start
