kind: pipeline
type: docker
name: default

steps:
  - name: install-dependencies-and-test
    image: node:21
    commands:
      - yarn install
      - yarn test

  - name: run-cypress-tests
    image: cypress/included:12.17.3
    commands:
      - yarn run cypress run
